In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

<h1>Importing the dataset</h1>
    <p>Create X for column of value use to predict dataset.iloc[: # Take all the range of row, : the all of the column except last one] </p>
    <p>Create Y for column of prediction dataset.iloc[:, -1].values</p>

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values # independent variable
y = dataset.iloc[:, -1].values # dependent variable last column

# Taking care of missing data

In [14]:
# Take care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') # replace missing data with mean
imputer.fit(X[:, 1:3]) # Get Metrix Of X with missing data
X[:,1:3] = imputer.transform(X[:, 1:3]) # Replace missing data with mean

# Encode category data


In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# encoder = OneHotEncoder()
X = np.array(ct.fit_transform(X))


<p>Each row of the name of country encoding to floating number</p>

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() # No need to use OneHotEncoder because y is dependent variable
y = le.fit_transform(y) # fit and transform y to 0,1 dependent variable yes or no
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [21]:
from sklearn.model_selection import train_test_split
# Splitting the dataset into the Training set and Test set
# split 20% for test set
# random_state = 1 means the same result for each run
# stratify = y means the same distribution for each run
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1, stratify=y)



In [29]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
# StandardScaler = (x-mean(x))/std(x)
# fit_transform = fit and transform
# fit = calculate mean and std
# transform = (x-mean(x))/std(x)
# fit_transform = calculate mean and std and (x-mean(x))/std(x)
# transform = (x-mean(x))/std(x) with mean and std from fit
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
# only transform because mean and std from fit
X_test[:, 3:] = sc.transform(X_test[:, 3:])
print(X_train)
print(X_test)

[[0.0 1.0 0.0 1.4810949949635102 1.5511947816430596]
 [1.0 0.0 0.0 -0.2115849992805015 0.15293469678171012]
 [1.0 0.0 0.0 -0.47199730608727253 -0.633586600952799]
 [1.0 0.0 0.0 0.6998580745431972 0.5898909733008818]
 [0.0 0.0 1.0 -1.5136465333143565 -1.5074991539911424]
 [0.0 1.0 0.0 -1.1230280731042 -0.9831516221681363]
 [1.0 0.0 0.0 1.2206826881567392 1.2016297604277222]
 [0.0 0.0 1.0 -0.081378845877116 -0.37141283504129596]]
[[0.0 1.0 0.0 40.0 63777.77777777779]
 [0.0 0.0 1.0 38.77777777777778 52000.00000000001]]


In [ ]:
# Training the Logistic Regression model on the Training set
from sklearn.linear_model import LogisticRegression
# penalty = 'l2' means Ridge Regression